export const SET_IS_LOGIN = 'AUTH/SET_IS_LOGIN'
export const SET_TOKEN = 'AUTH/SET_TOKEN'
export const SET_IS_REGISTERED = 'AUTH/SET_IS_REGISTERED'

export const SET_DIALOGS = 'DIALOGS/SET_DIALOGS'
export const SET_CURRENT_DIALOG = 'DIALOGS/SET_CURRENT_DIALOG'

export const SET_MESSAGES = 'MESSAGES/SET_MESSAGES'

export const SET_IS_FETCHING = 'SET_IS_FETCHING'
export const SET_ERRORS = 'SET_ERRORS'