export const SET_DIALOGS = 'DIALOGS/SET_DIALOGS'
export const SET_CURRENT_DIALOG = 'DIALOGS/SET_CURRENT_DIALOG'

export const SET_MESSAGES = 'MESSAGES/SET_MESSAGES'

export const SET_IS_FETCHING = 'SET_IS_FETCHING'